### ISSUE TITLE
Encountered children with the same key

### ISSUE THREAD

**Issue by dungdohoang** [AppAndFlow/react-native-masonry-list#10]
I am using MasonryList to show a list which can be switched between 1 and 2 columns. When there is just 1 column, it works normally without any errors or warnings. However, when I switch to 2 columns mode and scroll the list up, there are warnings prompting "Warning: flattenChildren(...): Encountered children with the same key".
In the keyExtractor function, I return the id of the the item. I dont think there are items with the same id.
I am a beginner in react native. So I have no idea where does this error comes from. 
Please help me. Thanks.

**Comment by JPig** [comment]
That error will only be shown if multiple components have the same key. You might want to double check the values you are using for the key or perhaps you are doing some kind of unwanted concat of the array and causing dupes that way?

**Comment by dungdohoang** [comment]
I found the reason. It is because onEndReached is triggered so many times, so the data returned is duplicated. Don't know why, so I worked around it.

**Comment by JPig** [comment]
Ahh okay true that would do it :)

**Comment by macrozone** [comment]
I have the same issue and its happends when i use hot-reload. After reloading i get as endless loop:

```
Warning: flattenChildren(...): Encountered two children with the same key, `-Kq8fxiEzneMg3CzeoK0`. Child keys must be unique; when two children share a key, only the first child will be used.
    in RCTView (at View.js:133)
    in View (at MasonryList.js:86)
    in FakeScrollView (at MasonryList.js:203)
    in VirtualizedList (at MasonryList.js:227)
    in RCTView (at View.js:133)
    in View (at MasonryList.js:225)
    in RCTScrollContentView (at ScrollView.js:668)
    in RCTScrollView (at ScrollView.js:751)
    in ScrollView (at MasonryList.js:108)
```

**Comment by janicduplessis** [comment]
Yes there is a known issue which onEndReached, it will be called once per column sadly. I don't have a timeline for a fix.

What I'm doing in my apps is adding a loading flag to prevent loading new data multiple times at once on onEndReached.

**Comment by janicduplessis** [comment]
I'll keep #13 open to track this issue
