### ISSUE TITLE
Use ListHeaderComponent

### ISSUE THREAD

**Issue by thenathan30** [AppAndFlow/react-native-masonry-list#12]
Hi !
I'm new with react native, i search now for 3hours and i don't no how to send data into the ListHeaderComponent.
because in my code I use :
`<MasonryList
        ListHeaderComponent={this.RenderMasonryHeader}
        ...`
and my RenderMasonryHeader is :
`RenderMasonryHeader(state) {
        return (
            <View>
                <CachedImage
                    source={{
                    uri: this.props.avatar
                }}/>
          </View>`

And I don't know how to send to this.props.
Please help meeee

**Comment by janicduplessis** [comment]
You can probably do something like:
```js
ListHeaderComponent={() => <View> <CachedImage source={{ uri: this.props.avatar }}/> </View>}
```
