### ISSUE TITLE
button in cell can not respond to the onPress event in time

### ISSUE THREAD

**Issue by Ben56** [AppAndFlow/react-native-masonry-list#9]
Pull down the data, some components are  mounting,some components are unmounting, this time the  button in cell can not respond to the onPress event in time, because android phone performance is not good, so the problem is more obvious

**Comment by janicduplessis** [comment]
Sorry I'm not sure the issue is related to this library. Looks more like an issue with React Native or VirtualizedList (which is the RN component used by this lib).

If you can get a repro of the bad performance I suggest posting an issue on the RN repo.
